# Generated by Django 4.2.11 on 2024-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specs', models.FileField(upload_to='faults_pics')),
            ],
        ),
        migrations.CreateModel(
            name='FaultUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(upload_to='faults_pics')),
            ],
        ),
    ]
