# Generated by Django 4.2.11 on 2024-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0002_fault_faultupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultupload',
            name='imageFile',
        ),
        migrations.AddField(
            model_name='faultupload',
            name='faultFile',
            field=models.FileField(blank=True, upload_to='faults_pics'),
        ),
    ]
