# Generated by Django 4.2.11 on 2024-03-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0003_remove_faultupload_imagefile_faultupload_faultfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fault',
        ),
        migrations.DeleteModel(
            name='FaultUpload',
        ),
    ]
